# Generated by Django 5.0.3 on 2024-03-25 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collage_management_app', '0006_alter_subject_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='updated_at',
        ),
    ]
