# Generated by Django 5.0.3 on 2024-06-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collage_management_app', '0017_attendance_attendance_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_report',
            name='student_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.DO_NOTHING, to='collage_management_app.student'),
        ),
        migrations.AlterField(
            model_name='attendance_report',
            name='Attendance_id',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='collage_management_app.attendance'),
        ),
    ]
